### ISSUE TITLE
NPE with a Kotlin-based project

### ISSUE THREAD

**Issue by juergenzimmermann** [IntershopCommunicationsAG/dependencyanalysis-gradle-plugin#9]
I'm getting a NPE using the `dependencyanalysis-gradle-plugin` 3.2.0 with a project using Kotlin. See the stacktrace below. My versions are as follows:
* gradle 4.4.1
* JDK 9.0.1
* Kotlin 1.2.10

The console Output and stacktrace:
```
[...]
> Task :classes UP-TO-DATE
Skipping task ':classes' as it has no actions.

:classes (Thread[Task worker for ':' Thread 2,5,main]) completed. Took 0.0 secs.
:jar (Thread[Task worker for ':' Thread 2,5,main]) started.

> Task :jar SKIPPED
Skipping task ':jar' as task onlyIf is false.

:jar (Thread[Task worker for ':' Thread 2,5,main]) completed. Took 0.0 secs.
:dependencyAnalysis (Thread[Task worker for ':' Thread 2,5,main]) started.

> Task :dependencyAnalysis FAILED
Putting task artifact state for task ':dependencyAnalysis' into context took 0.0 secs.

:dependencyAnalysis (Thread[Task worker for ':' Thread 2,5,main]) completed. Took 0.0 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dependencyAnalysis'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dependencyAnalysis'.
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:50)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.NullPointerException
        at com.intershop.gradle.analysis.model.Artifact.hashCode(Artifact.groovy:132)
        at com.intershop.gradle.analysis.task.DependencyAnalysisTask$_getJavaLibraryDependencies_closure3.doCall(DependencyAnalysisTask.groovy:224)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.intershop.gradle.analysis.task.DependencyAnalysisTask.getJavaLibraryDependencies(DependencyAnalysisTask.groovy:220)
        at com.intershop.gradle.analysis.task.DependencyAnalysisTask_Decorated.getJavaLibraryDependencies(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.api.internal.project.taskfactory.TaskPropertyInfo$2.create(TaskPropertyInfo.java:89)
        at org.gradle.util.SingleMessageLogger.whileDisabled(SingleMessageLogger.java:230)
        at org.gradle.api.internal.project.taskfactory.TaskPropertyInfo.getValue(TaskPropertyInfo.java:86)
        at org.gradle.api.internal.tasks.TaskPropertyValue.validate(TaskPropertyValue.java:38)
        at org.gradle.api.internal.tasks.DefaultTaskInputPropertySpec.validate(DefaultTaskInputPropertySpec.java:53)
        at org.gradle.api.internal.tasks.DefaultTaskInputs.validate(DefaultTaskInputs.java:168)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:47)
        ... 24 more
```

**Comment by m-raab** [comment]
I think, this is not an issue of a Kotlin build. Can you provide the main configuration of the build script, please?

**Comment by juergenzimmermann** [comment]
@m-raab I attached an almost empty project to reproduce the issue.
[tc-9.zip](https://github.com/IntershopCommunicationsAG/dependencyanalysis-gradle-plugin/files/1596132/tc-9.zip)

**Comment by m-raab** [comment]
Hi,
I checked the configuration. I think the behavior depends on the used configured Spring Boot plugin. The NPE occurs, because the version of a dependency is not configured. I think, the version of a dependency was not resolved from the Spring plugin before the dependency analysis runs.

**Comment by juergenzimmermann** [comment]
The Spring plugin `io.spring.dependency-management` provides a BOM mechanism so that dependencies can be declared like `'org.springframework.boot:spring-boot-starter-log4j2'`, i.e. without specifying the according version. The plugin `io.spring.dependency-management` enables `dependencyManagement {...}` where BOM files can be listed.

**Comment by juergenzimmermann** [comment]
@m-raab The issue is gone after upgrading the dependencyanalysis-gradle-plugin to 3.3.0

**Comment by juergenzimmermann** [comment]
Project is dead
